### ISSUE TITLE
Add return type to relationships

### ISSUE THREAD

**Issue by chinmaypurav** [m7md3omer/Vscode-extension-laravel-snippets#4]
Hi @mhmdomer, I was wondering if we could/should add return type to the snippets?

I usually keep almost everything type-hinted with no doc-blocks.

Just needed your opinion before I create any PR.

**Comment by mhmdomer** [comment]
Hi @chinmaypurav, yeah, I think it is a good idea, keeping in mind that some users may find it hard to import those classes (and we can't import those classes for them :( ), but they can delete it anyways. so feel free to add those types.
And thanks for your contributions :)

**Comment by mhmdomer** [comment]
I don't think it is a very good idea, I am trying to make it easy to use even for newcomers. If we add a return type, then all the users who don't have auto-import feature will suffer trying to figure out how to import those classes.
